version: "3.9"


services:

    mariadb:
        image: mariadb
        build: 
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        container_name: mariadb
        volumes:
            - db_volume:/var/lib/mysql
        restart: always
        networks:
            - inception
        env_file:
            - .env

    wordpress:
        image: wordpress
        build:
            context: ./requirements/wordpress/
            dockerfile: Dockerfile
        container_name: wordpress
        volumes:
            - wp_volume:/var/www/html
        depends_on:
            - mariadb
        networks:
            - inception
        restart: always
        env_file:
            - .env

    nginx:
        image: nginx
        build:
            context: ./requirements/nginx/
            dockerfile: Dockerfile
        container_name: nginx
        volumes:
            - wp_volume:/var/www/html
            - portfolio_volume:/var/www/portfolio
        ports:
            - "443:443"
        depends_on:
            - wordpress
        networks:
            - inception
        restart: always
      
    adminer:
        image: adminer
        build: 
            context: ./requirements/bonus/adminer/
            dockerfile: Dockerfile
        tty: true
        container_name: adminer
        volumes: 
            - wp_volume:/var/www/html
        depends_on: 
            - wordpress
        networks: 
            - inception
        restart: always

    ftp:
        image: ftp
        build:
            context: ./requirements/bonus/ftp/
            dockerfile: Dockerfile
        tty: true
        container_name: ftp
        volumes: 
            - wp_volume:/home/emabel
        ports:
            - 21100:21100
            - "20:20"
            - "21:21"
        depends_on: 
            - wordpress
        networks: 
            - inception
        restart: always

    portfolio:
        image: portfolio
        build:
            context: ./requirements/bonus/portfolio/
            dockerfile: Dockerfile
        container_name: portfolio
        ports:
            - "127.0.0.1:8001:80"
        networks: 
            - inception
        restart: always
        volumes: 
            - portfolio_volume:/var/www/portfolio

    


networks:
        inception:
            name: inception
            driver: bridge



volumes:
    wp_volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/emabel/data/wp
    db_volume:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: /home/emabel/data/db
    portfolio_volume:
            driver: local
            driver_opts:
                type: none
                o: bind
                device: /home/emabel/data/portfolio

